**Balavardhan Reddy Kotla**
**700765621**

**1) a**

In [1]:
import numpy as np

# 1. Create random vector
vector = np.random.randint(1, 21, size=15)
print("Original Vector:\n", vector)

# 2. Reshape to 3x5
reshaped = vector.reshape(3, 5)
print("Reshaped Array (3x5):\n", reshaped)

# 3. Replace max in each row with 0
for row in reshaped:
    row[np.argmax(row)] = 0
print("After replacing max in each row with 0:\n", reshaped)


Original Vector:
 [19 10  4 20  8  4 14 14 14  2 15 12  9 13  5]
Reshaped Array (3x5):
 [[19 10  4 20  8]
 [ 4 14 14 14  2]
 [15 12  9 13  5]]
After replacing max in each row with 0:
 [[19 10  4  0  8]
 [ 4  0 14 14  2]
 [ 0 12  9 13  5]]


**b.  2D array and metadata**

In [2]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype=np.int32)
print("2D Array:\n", array_2d)
print("Shape:", array_2d.shape)
print("Type:", type(array_2d))
print("Data Type:", array_2d.dtype)


2D Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data Type: int32


**C. Eigenvalues and eigenvectors**

In [3]:
matrix = np.array([[3, -2],
                   [1, 0]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:\n", eigenvalues)
print("Right Eigenvectors:\n", eigenvectors)


Eigenvalues:
 [2. 1.]
Right Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


**d. Sum of diagonal elements**

In [4]:
array = np.array([[0, 1, 2],
                  [3, 4, 5]])
diagonal_sum = np.trace(array)
print("Sum of diagonal elements:", diagonal_sum)


Sum of diagonal elements: 4


**e. Reshape without changing data**

In [6]:
original = np.array([[1, 2],
                     [3, 4],
                     [5, 6]])
reshaped = original.reshape(2, 3)
print("Reshaped to 2x3:\n", reshaped)


Reshaped to 2x3:
 [[1 2 3]
 [4 5 6]]
